name: Docker Build

on:
  pull_request:
    branches:
      - 'main'

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jinaga/jinaga-replicator
          tags: |
            type=ref,event=pr
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build no-security-policies image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.no-security-policies
          platforms: linux/amd64,linux/arm64
          push: false
          tags: jinaga/jinaga-replicator-no-security-policies:latest
