version: '3.8'

services:
  front-end-replicator:
    image: jinaga/jinaga-replicator-no-security-policies
    container_name: front-end-replicator
    ports:
      - "8080:8080"
    networks:
      - replicator-network

  back-end-replicator:
    image: jinaga/jinaga-replicator-no-security-policies
    container_name: back-end-replicator
    ports:
      - "8081:8080"
    environment:
      - REPLICATOR_UPSTREAM_1=http://front-end-replicator:8080/jinaga
    networks:
      - replicator-network

networks:
  replicator-network:
    driver: bridge
